############################################################################
#
#  Primary targets:
#    all           - the default target; synonym for 'coq'
#    coq           - builds all .vo files
#    doc           - synonym for 'documentation'
#    documentation - builds all html documentation
#    clean         - removes generated files
#
#  Other targets (intended to be used by the developers of this library):
#    gens          - builds generated .v files on demand
#    dist          - builds a zip file for distribution
#
############################################################################

## Paths to executables. Do not include options here.
## Modify these to suit your Coq installation, if necessary.

## If you get warnings such as:
## *** Warning: in file AssocList.v, library CoqFSetDecide is required and has not been found in the loadpath!
## you can use a shell variable to set the load path. (Somehow the -I below is being ignored.)
## export COQPATH=.

COQC = coqc
COQDEP = coqdep
COQDOC = coqdoc


## Library name used for the imports in Coq

LIBNAME=Metalib

## Name of the submakefile generated by coq_makefile

COQMKFILENAME=CoqSrc.mk

## Include directories, one per line.

INCDIRS = \
	.

## Directory where generated HTML documentation should go.

DOCDIR = doc/html

## List of files to be compiled and documented.
# TODO: should be useless once we get coq_makefile to compile the documentation as well

FILES = \
	AssocList \
	CoqEqDec \
	CoqFSetDecide \
	CoqFSetInterface \
	CoqListFacts \
	CoqUniquenessTac \
	CoqUniquenessTacEx \
	FSetExtra \
	FSetWeakNotin \
	LibDefaultSimp \
	LibLNgen \
	LibTactics \
	\
	MetatheoryAtom \
	Metatheory \
	\
	AssumeList \
	MetatheoryAlt \
	\
	Fsub_LetSum_Definitions \
	Fsub_LetSum_Infrastructure \
	Fsub_LetSum_Lemmas \
	Fsub_LetSum_Soundness \
	\
	CoqIntro \
	STLCsol \

## Lists calculated from the above.

VFILES   = $(foreach i, $(FILES), $(i).v)
VOFILES  = $(foreach i, $(FILES), $(i).vo)
INCFLAGS = $(foreach i, $(INCDIRS), -I $(i))

############################################################################

.PHONY: all clean coq dist doc documentation gens
.SUFFIXES: .v .vo

all: coq # Metatheory.vo MetatheoryAlt.vo LibLNgen.vo

#coq: $(VOFILES)
coq: $(COQMKFILENAME)
	# FIXME: loose integration right now, but when the doc works we should be able to simply include the generated makefile
	@$(MAKE) -f CoqSrc.mk

$(COQMKFILENAME): Makefile
	{ echo "-R . $(LIBNAME) " ; ls *.v ; } > _CoqProject && coq_makefile -f _CoqProject -o $(COQMKFILENAME)

# TODO: in theory, coq_makefile creates targets for documentation, so we should be able to use it instead of handwritten rules
doc:
	+make documentation

documentation: $(DOCDIR) $(VOFILES)
	$(COQDOC) -g --quiet --noindex --html -d $(DOCDIR) $(VFILES)
	cp -f custom.css $(DOCDIR)/coqdoc.css

clean:
	#rm -f *.vo *.glob *.cmi *.cmx *.o
	@$(MAKE) -f CoqSrc.mk clean
	rm -rf $(DOCDIR)

############################################################################

%.vo: %.v Makefile
	$(COQC) -q $(INCFLAGS) $<

$(DOCDIR):
	mkdir -p $(DOCDIR)

############################################################################

# Not necessary anymore
# .depend: $(VFILES) Makefile
# 	$(COQDEP) $(INCFLAGS) $(VFILES) > .depend
#
# include .depend

############################################################################

DATE = $(shell date +%Y%m%d)
DIR  = metalib-$(DATE)

COQSPLIT = ../../books/sf/tools/coqsplit
STLC = ../../books/coqbook/stlc/STLC.v

gens:
	make -C ../../books/sf tools/coqsplit
	$(COQSPLIT) < $(STLC) > STLC.v
	$(COQSPLIT) -solutions < $(STLC) > STLCsol.v

dist:
	svn export . $(DIR)
	(cd $(DIR); $(MAKE) documentation)
	rm -f $(DIR)/*.vo $(DIR)/*.glob
	rm -f $(DIR)/TODO.txt
	echo Release $(DATE) / svn revision `svnversion .` >> $(DIR)/VERSION
	zip -r $(DIR).zip $(DIR)
	@echo
	@echo Done.
	@echo See $(DIR) and $(DIR).zip.
